// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIFH5nGBxSqaUutzC_xiWTqaqEZTZTix8',
    appId: '1:724502878457:web:c249879be0d696f54dea28',
    messagingSenderId: '724502878457',
    projectId: 'messhub-b7a30',
    authDomain: 'messhub-b7a30.firebaseapp.com',
    storageBucket: 'messhub-b7a30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9VSZMj9sPUJ0jnFw2uhCxfBVV8MvmdzM',
    appId: '1:724502878457:android:c1aacfdf7d5944144dea28',
    messagingSenderId: '724502878457',
    projectId: 'messhub-b7a30',
    storageBucket: 'messhub-b7a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzqpNcu_QeRJ-mhpGR2WZ7Wmv_OKSCGE',
    appId: '1:724502878457:ios:e87d932564de9ba64dea28',
    messagingSenderId: '724502878457',
    projectId: 'messhub-b7a30',
    storageBucket: 'messhub-b7a30.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzqpNcu_QeRJ-mhpGR2WZ7Wmv_OKSCGE',
    appId: '1:724502878457:ios:f78780a99ae9f9a54dea28',
    messagingSenderId: '724502878457',
    projectId: 'messhub-b7a30',
    storageBucket: 'messhub-b7a30.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
